In [1]:
import numpy as np
import pandas as pd
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

from xgboost import XGBRegressor

/kaggle/input/competitions/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/competitions/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/competitions/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/competitions/house-prices-advanced-regression-techniques/test.csv

In [2]:
train = pd.read_csv("/kaggle/input/competitions/house-prices-advanced-regression-techniques/train.csv")
test = pd.read_csv("/kaggle/input/competitions/house-prices-advanced-regression-techniques/test.csv")
test_ids = test["Id"]

In [3]:
y_train = train["SalePrice"]
X_train = train.drop(["Id", "SalePrice"], axis = 1)
all_cols = X_train.columns
X_train = pd.get_dummies(X_train, columns=all_cols)

In [4]:
X_train

,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
2,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1456,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1457,False,False,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1458,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1459,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False

In [5]:
model = XGBRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

In [6]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=None, num_parallel_tree=None, ...)

In [7]:
X_test = test.drop("Id", axis=1)
test_cols = X_test.columns
X_test = pd.get_dummies(X_test, columns=test_cols)

In [8]:
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [9]:
X_test

,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
2,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
3,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1455,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1456,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1457,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,False
1458,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False

In [10]:
pred = model.predict(X_test)

In [11]:
pred

array([124098.66, 153770.06, 180107.11, ..., 139202.55, 120882.7 ,
       194560.25], dtype=float32)

In [12]:
submission = pd.DataFrame({
    "Id": test_ids,
    "SalePrice": pred
})
submission.to_csv("submission.csv", index = False)

In [13]:
submission

        Id      SalePrice
0     1461  124098.656250
1     1462  153770.062500
2     1463  180107.109375
3     1464  191426.265625
4     1465  187289.484375
...    ...            ...
1454  2915   99155.843750
1455  2916   85702.710938
1456  2917  139202.546875
1457  2918  120882.703125
1458  2919  194560.250000

[1459 rows x 2 columns]